draft-privacy-token.md
=> Expand KeyID, and clarify its format.

draft-private-access-tokens.md
Details about the trust model are perhaps next most important.
=> Add examples and more considerations.

draft-private-access-tokens.md
Larger feedback will come as issues
=> First read nits

draft-private-access-tokens.md
Closes #20, making interactive the only mode.
=> Make PATs interactive.

draft-private-access-tokens.md
=> Update authors for Private Access Tokens.

draft-private-access-tokens.md
=> Make the PrivateAccessToken format stand-alone

draft-private-access-tokens.md
Feels a bit wordy. @dvorak42, is there a specific link for the privacy promises of privacy pass?
Should we just use https://datatracker.ietf.org/doc/draft-ietf-privacypass-protocol/ ?
=> Add single issuer-mediator considerations

draft-private-access-tokens.md
Closes #44 
Closes #19 
Closes #14
=> Expand token security considerations

draft-private-access-tokens.md
=> Make token keys per-origin

draft-private-access-tokens.md
Fixes #59, and offers a couple of modifications elsewhere.
=> Nits and fix

draft-private-access-tokens.md
The NIZK proof section is sort of dangling on its own, so we may want to further shuffle things around. What do folks think about this structure?
=> Dependency pointers and implementation requirement clarification

draft-private-access-tokens.md
=> Add section on Client identity

draft-private-access-tokens.md
Describe client state loss procedures
Tried to centralize this within the state requirements, and mentioned in the client-to-mediator flow.
=> Client state loss

draft-private-access-tokens.md
=> Rename name_key_id to issuer_key_id

draft-privacypass-rate-limit-tokens.md
I'm still working on the analysis of this, but this is at least more descriptive than it was in the other PR.
=> Clean up request signature section

draft-privacypass-rate-limit-tokens.md
=> Define Attester URI template

draft-privacypass-rate-limit-tokens.md
=> Update config key

draft-privacypass-rate-limit-tokens.md
=> Try out moving the limit enforcement to the Attester

draft-privacypass-rate-limit-tokens.md
Turns out we already had the text! =)
Closes #111.
=> Point to the rotation section

draft-pauly-privacypass-auth-scheme.md, draft-privacypass-rate-limit-tokens.md
=> Issuer key => token key

draft-pauly-privacypass-auth-scheme.md
Based on discussion during the interim meeting.
=> Add text around the timing considerations

draft-privacypass-rate-limit-tokens.md
=> Use ECDSA instead of Ed25519

draft-privacypass-rate-limit-tokens.md
=> Fix text around directionality of token count

draft-privacypass-rate-limit-tokens.md
=> Address nits from Tancrede

draft-privacypass-rate-limit-tokens.md
=> Clarify security requirements and properties

draft-privacypass-rate-limit-tokens.md
=> Pad the origin name (using the ECH policy)

draft-privacypass-rate-limit-tokens.md
Good to publish -00 after this, I think.
=> Fix KEYBLINDING reference

draft-privacypass-rate-limit-tokens.md
#183 
Also link to the work of the antifraud cg
=> Describe why basic issuance is insufficient

draft-privacypass-rate-limit-tokens.md
=> Specify requirements to keep origin names private from attesters

draft-privacypass-rate-limit-tokens.md
Closes #185.
We can add more once the security analysis is complete.
=> Add text on malicious and HbC protocol participants

draft-privacypass-rate-limit-tokens.md
I likely won't have time to generate test vectors for EdDSA today, but we can always add them later.
=> Support EdDSA along with ECDSA

draft-privacypass-rate-limit-tokens.md
=> Align token-keys configuration

draft-privacypass-rate-limit-tokens.md
=> Add more discussion on attester's role in key consistency

draft-privacypass-rate-limit-tokens.md
=> Add Origin IDs

draft-privacypass-rate-limit-tokens.md
=> Address token<>origin binding with per-Origin Token Keys

draft-pauly-masque-dns-proxy-status.md
=> Add percent encoding for commas in CNAMEs

draft-pauly-httpbis-alias-proxy-status.md
=> Remove SVCB reference

draft-pauly-intarea-proxy-config-pvd.md
Address feedback from IETF 118 to allow more information for proxies, and be explicit on proxy protocol
=> Make proxies a sub-dictionary

draft-ietf-intarea-proxy-config.md
=> Add explicit keys for match and exclude domains

draft-ietf-intarea-proxy-config.md
=> Describe updating a known HTTP proxy to a secure HTTP proxy.

draft-ietf-intarea-proxy-config.md
Change excludedDomains into excludeDomains to match matchDomains.
This should resolve #254 and #255 .
=> Clarify that exclusions can be specified without any match domains

draft-ietf-intarea-proxy-config.md
Added a definition of proprietary keys for `proxies` and destination rules
=> Proprietary keys

draft-ietf-intarea-proxy-config.md
I have collapsed all my suggestions from https://github.com/tfpauly/privacy-proxy/pull/276 into a fresh PR so it could be readable.
=> Match/exclude destination rules (flattened)

draft-ietf-intarea-proxy-config.md
=> Tell experts not to allow underscores in keys

draft-ietf-intarea-proxy-config.md
=> Allow IP subnet rules to apply to resolved names

draft-ietf-intarea-proxy-config.md
=> Clarify that the proxy should be reuse.
