draft-privacy-token.md

The usual reference format ({{I-D.foo.bar}}) doesn't work probably because the draft is still new. But this at least points folks to the right place.

Fix the RSA Blind Signature reference.

---

draft-proxied-svcb-headers.md

Significant changes and clarifications, renaming the existing headers and ending up with three headers:
* Proxy-DNS-Request
* Proxy-DNS-SVCB
* Proxy-DNS-Used
Also specify client behavior to allow SVCB-optional clients to use proxies implementing these features while incorporating performance optimizations.

Significant changes for Proxy DNS and SVCB request/response handling

---

draft-private-access-tokens.md

It felt like we were trying to express linkability and private authentication in a single case. This splits the cases into their own sections for clarity.

Split up 'client re-identification' into two use cases

---

draft-private-access-tokens.md

I've not restructured much yet, but did an editorial pass of the Intro and Overview sections.
Next, I intend to:
- move a version of the Use Cases Section up to after the Intro Section.
- add a picture to the Overview Section describing this architecture. I might try to break out the Overview into a Functional Overview and a Protocol Overview.
We should consider a name for the architecture. It's all about Private Address Tokens, but that's not the architecture or the protocol name.

First pass through Intro and Overview sections

---

draft-private-access-tokens.md

I don't love the geolocation exchange here. Mediators probably should not send anything that client's don't want them to send, so maybe that means clients opt-in to allowing their geohash to be forwarded. And maybe they decide to do that if Origins request tokens that need to be region specific? (Origins could maybe send that via the Accept-CH header in their challenge, and Clients could use that to send to the Mediator? I dunno.)
I also cut Client Linking as a use case.

Describe how to instantiate motivating use cases

---

draft-private-access-tokens.md

This brings up a few more questions:
- Should we update the API Endpoints section to contain APIs for querying these keys per origin?
- Does the ISSUER_KEY need a well defined rotation policy?
#57 related

ORIGIN_TOKEN_KEY rotation deployment info

---

draft-private-access-tokens.md

The only remaining piece of "crypto" in the issuance flow description is the blind RSA bits. I'm not yet sure what we want to do with that, but I feel like this sort of extraction is useful for clarity. I'm happy to hear alternative proposals for presentations, too!
Closes #101.
cc @FredericJacobs

Isolate mapping computation to simplify presentation

---

draft-privacypass-rate-limit-tokens.md

The prefix wasn't randomized before, so two messages from the same secret key would carry the same `R` component. [Gist](https://gist.github.com/chris-wood/a089ca863c14554e8e5912dda37570b9) updated to match.

Nonce randomization too

---

draft-privacypass-rate-limit-tokens.md

The NameKey fully defines the algorithms and key used for encrypting origins, as well as the corresponding key ID. Clients use these keys entirely or not, meaning there's no client-side negotiation. Since the key ID fully defines the key and algorithms, clients do not need to convey anything beyond the key ID to issuers in their TokenRequest.
Closes #124.
Closes #112.

Drop OHTTP dependency and redefine the name configuration

---

draft-privacypass-rate-limit-tokens.md

This uses functions in the key blinding draft directly, simplifying presentation. It does not change the signature scheme used from Ed25519 (to something else), yet. If we want to do that, it can happen in a followup change.
Closes #148.
cc @FredericJacobs

Adopt key blinding functions

---

draft-privacypass-rate-limit-tokens.md

We could just choose to encode ECDSA signatures in a separate format, like `r || s`, where `r` and `s` are both fixed-length 384-bit integers.
cc @FredericJacobs

Deal with variable-length ECDSA signatures

---

draft-privacypass-rate-limit-tokens.md

Align origin_name with auth scheme, allow for empty name

---

draft-privacypass-rate-limit-tokens.md

Turns out this doesn't affect the test vectors after all since we don't have vectors that cover the request signature path. 
Closes #202.

Sign the entire request wire format

---

draft-privacypass-rate-limit-tokens.md

cc @FredericJacobs 
See the corresponding change [here](https://github.com/cloudflare/pat-go/pull/18/commits/36d6705816141f305e7cba6425639b502d50bad8).

Use the key blinding contexts (and keep them separate)

---

draft-ietf-intarea-proxy-config.md

Variations between PAC file parsing by different JavaScript engine is a major issue... Some software even has to carry around full blown JavaScript engine just to parse PAC files as system libraries cannot always be trusted.
Let's call this out.

JavaScript engine inconsistencies is the biggest problem with PAC files

---

draft-ietf-intarea-proxy-config.md

This makes format extensible in the future and allows proprietary extensions.
On top of that it addresses the question of what clients should do if they cannot fully process proxy destination restrictions. If corresponding key is in `mandatory` list, they must ignore the proxy, otherwise they may proceed even without full processing of the destination restriction list.

Added mandatory key

---

draft-ietf-intarea-proxy-config.md

As discussed at IETF121 I merged matchPorts into other matching criteria. Adjusted examples and wording accordingly.

Port matching rework

---

draft-ietf-intarea-proxy-config.md

Closes #288 
Fixes a bug in the spec where in an example, we showed fetching the PvD from a non-TLS port. We need to use a single PvD config per hostname.

Clarify which port to fetch the PvD on

---

draft-ietf-intarea-proxy-config.md

Added two more examples to cover constraints of proxy protocols, default proxy configuration as well as ordered list of proxies.
Corrected content-length in the very first example (I suppose we should count whitespace and line breaks if we include them in the text)
Corrected previous examples:
- clarified traffic protocols
- ports are strings. Added a range of ports in the example to make it obvious

Added more examples and corrected existing ones

---

draft-pauly-httpbis-geoip-hint.md

This PR adds the OHTTP use case to the geoIP draft, and mentions that this is intended for specific use cases and not general browsing. It also removes some of the early text on client hint since that's not the focus of the background/motivation.

GeoIP: Add OHTTP use case to motivation
